name: Prepare F-Droid Branch

on:
  workflow_dispatch:

jobs:
  prepare-fdroid:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Move App Contents to Root and Clean Up
        run: |
          rm -rf .github  # Remove GitHub Actions folder
          rm -f .gitignore  # Remove .gitignore if present
          mv app/* .  # Move all files inside app/ to the root
          rm -rf app  # Remove the now-empty app directory

      - name: Commit and Push to fdroid Branch
        run: |
          git config --global user.name "theSoberSobber"
          git config --global user.email "pavitchhabra1611@gmail.com"
          git checkout -B fdroid
          git add .
          git commit -m "Prepare F-Droid branch: Move app to root and clean up"
          git push origin fdroid --force
