name: Prepare F-Droid Branch

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  prepare-fdroid:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Move App Contents to Root and Clean Up
        run: |
          # Remove GitHub Actions workflow folder
          rm -rf .github  
          
          # Remove .gitignore if present
          rm -f .gitignore  
          
          # Move all files and hidden files from app/ to root
          shopt -s dotglob nullglob  # Enable moving hidden files
          mv app/* app/.* . || true  # Ignore errors if no hidden files exist
          
          # Remove the now-empty app directory
          rm -rf app  

      - name: Commit and Push to fdroid Branch
        run: |
          git config --global user.name "theSoberSobber"
          git config --global user.email "pavitchhabra1611@gmail.com"
          git checkout -B fdroid
          git add .
          git commit -m "Prepare F-Droid branch: Move app to root and clean up"
          git push origin fdroid --force
