name: Prepare F-Droid Branch

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  prepare-fdroid:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Remove Everything Except App, Screenshots, README, and LICENSE
        run: |
          shopt -s extglob  # Enable pattern matching
          
          # Move required files to a safe location
          mkdir /tmp/keep
          mv app screenshots README.md LICENSE /tmp/keep/ 2>/dev/null || true
          
          # Delete everything in the repo
          rm -rf * .[^.]* 2>/dev/null || true
          
          # Move app contents to root
          mv /tmp/keep/app/* /tmp/keep/app/.* . 2>/dev/null || true
          
          # Restore screenshots, README.md, and LICENSE
          mv /tmp/keep/screenshots /tmp/keep/README.md /tmp/keep/LICENSE . 2>/dev/null || true
          
          # Remove temporary app folder
          rm -rf /tmp/keep/app /tmp/keep

      - name: Commit and Push to fdroid Branch
        run: |
          git config --global user.name "theSoberSobber"
          git config --global user.email "pavitchhabra1611@gmail.com"
          git checkout -B fdroid
          git add .
          git commit -m "Prepare F-Droid branch: Keep only app, screenshots, README.md, and LICENSE"
          git push origin fdroid --force
